#!/bin/bash

# Disable storage automounting (/usr/lib/udisks2/udisks2-inhibit)
sudo mkdir -p /run/udev/rules.d
sudo sh -c 'echo "SUBSYSTEM==\"block\", ENV{UDISKS_IGNORE}=\"1\"" > /run/udev/rules.d/90-udisks-inhibit.rules'
trap "sudo rm -f /run/udev/rules.d/90-udisks-inhibit.rules; sudo udevadm control --reload; sudo udevadm trigger --subsystem-match=block" EXIT HUP INT QUIT ILL ABRT FPE KILL SEGV PIPE ALRM TERM BUS
sudo udevadm control --reload
sudo udevadm trigger --subsystem-match=block

exec "$@"
